{% set version = "3.4.0" %}

package:
  name: gsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: d45c835af0e539235e9cf46ae58d9447e206d145b13ecfe7447ad7b8fbdcf86d

build:
  number: 0
  skip: True  # [py<=34]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
    - pytest
  imports:
    - gsw
    - gsw.ice
  commands:
    - pip check
    - pytest --pyargs gsw

about:
  home: https://github.com/TEOS-10/GSW-Python/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Gibbs SeaWater Oceanographic Package of TEOS-10'

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
