schema_version: 1

context:
  version: "3.6.21"
  python_min: "3.11"

package:
  name: gsw
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gsw/gsw-${{ version }}.tar.gz
  sha256: 6e0609d374916b4393484b9c7b32666d36dda74d900a40d19c766484ac295efa

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - cross-python_${{ target_platform }}
        - numpy >=2,<3
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python ${{ python_min }}.*
    - python-abi3
    - numpy >=2,<3
    - pip
    - setuptools >=42
    - setuptools-scm >=3.4
  run:
    - python
    - numpy

tests:
  - python:
      imports: gsw
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - abi3audit
        - pytest
        - pandas >=2
    script:
      - pytest --pyargs gsw
      - if: unix
        then:
          - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
          - abi3audit $SP_DIR/gsw/_gsw_ufuncs.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
      - if: win
        then:
          - set "SP_DIR=%PREFIX%\\Lib\\site-packages"
          - abi3audit %SP_DIR%\\gsw\\_gsw_ufuncs.pyd -s -v --assume-minimum-abi3 ${{ python_min }}

about:
  summary: Gibbs Seawater Oceanographic Package of TEOS-10
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/gsw/

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
